### ISSUE TITLE
Difference with ZeroOmega?

### ISSUE THREAD

**Issue by stokito** [mrfanii/SwitchyOmega-V3#1]
There is another more popular fork of the SwitchyOmega:
* https://chromewebstore.google.com/detail/proxy-switchyomega-3-zero/pfnededegaaopdmhkdmcofjmoldfiped
* https://github.com/suziwen/ZeroOmega

It has more commits so maybe you can join them instead of maintain the own fork?

**Comment by womail123** [comment]
I recommend using the [zeroOmega](https://github.com/suziwen/ZeroOmega) version

I roughly looked at the  SwitchyOmega-V3's code, and found that they all used zeroOmega code which has commit earlier, but deliberately erased the commit history of the zeroOmega author, and then changed the software name. I suspect there will be some bad intentions in the future.

If there is anything wrong with what I said, I hope the author comes out and replies to clarify. If my guess is correct, please respect the GPL open source spirit and keep the modification history of ZeroOmega author suziwen. Respect other people's efforts.

**Comment by womail123** [comment]
There doesn't seem to be any malicious intent at the moment, 
 
 but the author deliberately cleared the fruits of others' labor without mentioning it in the readme.

This requires the author to give a reasonable explanation.

**Comment by womail123** [comment]
There doesn't seem to be any malicious intent at the moment, 
 
 but the author deliberately cleared the fruits of others' labor without mentioning it in the readme.

This requires the author @mrfanii  to give a reasonable explanation.

**Comment by mrfanii** [comment]
Thank you for bringing this to my attention, and I appreciate the feedback from both of you.

I’d like to clarify a few points:

    Regarding the History and Code:
    The fork I created, SwitchyOmega-V3, was intended to address specific needs and updates that were not covered in other forks. While I did use some of the code from ZeroOmega, I did not deliberately erase the commit history with any bad intentions. My focus was on making a functional and updated version for users who needed it.

    Commit History:
    If there are any missing attributions, I apologize for the oversight. My intention is to fully respect the GPL license and the efforts of other developers. I will review the commit history and make sure that any contributions from ZeroOmega and other sources are properly acknowledged.

    Future Plans:
    I plan to dedicate more time in the future to improve both the appearance and functionality of this project. I want to ensure it meets the community’s needs and expectations. If there are any suggestions or ideas, I’m open to hearing them.

    Collaboration:
    I am open to collaborating with the ZeroOmega maintainers if they are interested. The goal is to benefit the community, and working together could be a productive way forward.

Thank you again for raising these concerns. I hope this clarifies the situation, and I welcome any further discussion or suggestions.

Thanks,
mrfani

**Comment by mrfanii** [comment]
@stokito Thank you for your thoughtful response.

I understand your concerns about fragmentation and the potential benefits of consolidating efforts. While I respect and appreciate the work being done on ZeroOmega, my focus remains on improving and maintaining SwitchyOmega-V3. I believe this project can address specific needs that may not be fully covered by other forks.

However, I will make sure to clearly communicate to users that ZeroOmega is a well-supported alternative, so they can make informed decisions based on their needs. My priority is to ensure that users have access to the tools that best serve their requirements, whether that’s through SwitchyOmega-V3 or another project.

While I may not be able to contribute directly to ZeroOmega, I am still open to collaboration and discussions on how we can best serve the community’s needs.

Thank you again for your input, and I look forward to further discussions

**Comment by mainlibs** [comment]
It seems that it is not clearly explained **what is the difference between the current and zeroomega**. **Zeroomega was released about 5 months ago**, and you already know that there is a zeroomega version, but you still release a product with the same functions on the chrome store?
